Repository yisheng112358/WeMatch, pull requests merged in 2020-09, with the labels that each got.

#35 Product browsing page
  Develop/README.text
  Develop/SQLResource/create_table.sql
  Develop/WebContent/ProductsBrowsePage.jsp
  Develop/WebContent/WEB-INF/web.xml
  Develop/WebContent/js/ProductBrowserPage.js
  Develop/pom.xml
  Develop/resource/massager/massager1_d.jpg
  Develop/resource/massager/massager1_t.jpg
  Develop/resource/massager/massager2_d.jpg
  Develop/resource/massager/massager2_t.jpg
  Develop/resource/massager/massager3_d.jpg
  Develop/resource/massager/massager3_t.jpg
  Develop/resource/massager/massager4_d.jpg
  Develop/resource/massager/massager4_t.jpg
  Develop/resource/massager/massager5_d.jpg
  Develop/resource/massager/massager5_t.jpg
  Develop/resource/supplement/protein1_d.jpeg
  Develop/resource/supplement/protein1_t.jpeg
  Develop/resource/supplement/protein2_d.jpeg
  Develop/resource/supplement/protein2_t.jpeg
  Develop/resource/supplement/protein3_d.jpeg
  Develop/resource/supplement/protein3_t.jpeg
  Develop/resource/supplement/protein4_d.jpeg
  Develop/resource/supplement/protein4_t.jpeg
  Develop/resource/supplement/protein5_d.jpeg
  Develop/resource/supplement/protein5_t.jpeg
  Develop/resource/yoga/yoga1_d.jpg
  Develop/resource/yoga/yoga1_t.jpg
  Develop/resource/yoga/yoga2_d.jpg
  Develop/resource/yoga/yoga2_t.jpg
  Develop/resource/yoga/yoga3_d.jpg
  Develop/resource/yoga/yoga3_t.jpg
  Develop/resource/yoga/yoga4_d.jpg
  Develop/resource/yoga/yoga4_t.jpg
  Develop/resource/yoga/yoga5_d.jpg
  Develop/resource/yoga/yoga5_t.jpg
  Develop/src/hibernate.cfg.xml
  Develop/src/tw/eeit117/wematch/product/BaseServlet.java
  Develop/src/tw/eeit117/wematch/product/Product.java
  Develop/src/tw/eeit117/wematch/product/RetrieveProductServlet.java
  Develop/src/tw/eeit117/wematch/product/TestProductsGenerator.java
Labels: enhancement

#44 Eason use filter to manage session factory
  Develop/WebContent/WEB-INF/web.xml
  Develop/WebContent/js/ProductBrowserPage.js
  Develop/src/hibernate.cfg.xml
  Develop/src/tw/eeit117/wematch/jdbc/JdbcConnServlet.java
  Develop/src/tw/eeit117/wematch/jdbc/SignUpJdbcConnServlet.java
  Develop/src/tw/eeit117/wematch/jdbc/TestHomeWork.java
  Develop/src/tw/eeit117/wematch/jdbc/TestReadFile.java
  Develop/src/tw/eeit117/wematch/member/TestMembersGenerator.java
  Develop/src/tw/eeit117/wematch/product/RetrieveProductServlet.java
  Develop/src/tw/wematch/util/HibernateUtil.java
  Develop/src/tw/wematch/util/OpenSessionViewFilter.java
Labels: enhancement

#49 Eason spring mvc for product browsing
  Develop/WebContent/ProductsBrowsePage.jsp
  Develop/WebContent/WEB-INF/beans.config.xml
  Develop/WebContent/WEB-INF/hibernate.cfg.xml
  Develop/WebContent/WEB-INF/web.xml
  Develop/WebContent/favicon.ico
  Develop/WebContent/js/ProductBrowserPage.js
  Develop/src/Hibernate.properties
  Develop/src/TableName.properties
  Develop/src/hibernate.cfg.xml
  Develop/src/tw/eeit117/wematch/config/SpringJavaConfig.java
  Develop/src/tw/eeit117/wematch/config/SpringMVCJavaConfig.java
  Develop/src/tw/eeit117/wematch/config/WebAppInitializer.java
  Develop/src/tw/eeit117/wematch/product/TestProductsGenerator.java
  Develop/src/tw/eeit117/wematch/product/model/IProductBeanDAO.java
  Develop/src/tw/eeit117/wematch/product/model/IProductBeanService.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBean.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBeanDAO.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBeanService.java
Labels: enhancement

#50 Eason spring mvc for product browsing 2
  Develop/WebContent/WEB-INF/beans.config.xml
  Develop/WebContent/WEB-INF/resources/images/image01.jpg
  Develop/WebContent/WEB-INF/web.xml
  Develop/WebContent/js/ProductBrowserPage.js
  Develop/src/hibernate.cfg.xml
  Develop/src/tw/eeit117/wematch/config/SpringMVCJavaConfig.java
  Develop/src/tw/eeit117/wematch/config/WebAppInitializer.java
  Develop/src/tw/eeit117/wematch/config/WebAppMvcConfig.java
  Develop/src/tw/eeit117/wematch/product/controller/RetrieveProductController.java
Labels: enhancement

#58 Eason add product remove feature
  Develop/WebContent/SignUpPage.jsp
  Develop/WebContent/js/ProductBrowserPage.js
  Develop/WebContent/js/ProductManagePage.js
  Develop/src/tw/eeit117/wematch/product/controller/ProductController.java
  Develop/src/tw/eeit117/wematch/product/model/IProductBeanService.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBeanDAO.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBeanService.java
Labels: enhancement

#60 Eason unify product pages
  Develop/WebContent/ProductsSearchPage.jsp
  Develop/WebContent/WEB-INF/pages/CSSsetting.jsp
  Develop/WebContent/WEB-INF/pages/JSsetting.jsp
  Develop/WebContent/WEB-INF/pages/ProductAddPage.jsp
  Develop/WebContent/WEB-INF/pages/ProductsBrowsePage.jsp
  Develop/WebContent/WEB-INF/pages/ProductsManagePage.jsp
  Develop/WebContent/WEB-INF/pages/ProductsSearchPage.jsp
  Develop/WebContent/WEB-INF/pages/footer.jsp
  Develop/WebContent/WEB-INF/pages/header.jsp
  Develop/WebContent/js/ProductManagePage.js
  Develop/src/tw/eeit117/wematch/product/controller/ProductController.java
Labels: enhancement

#62 Eason display product pages via temp member status
  Develop/WebContent/WEB-INF/pages/ProductAddPage.jsp
  Develop/WebContent/WEB-INF/pages/ProductsBrowsePage.jsp
  Develop/WebContent/WEB-INF/pages/header.jsp
  Develop/WebContent/WEB-INF/web.xml
  Develop/WebContent/index.jsp
  Develop/src/tw/eeit117/wematch/product/controller/ProductController.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBean.java
Labels: enhancement

#63 Eason product exam page
  Develop/WebContent/WEB-INF/pages/ProductExamPage.jsp
  Develop/WebContent/index.jsp
  Develop/WebContent/js/ProductBrowserPage.js
  Develop/src/tw/eeit117/wematch/product/controller/ProductController.java
  Develop/src/tw/eeit117/wematch/product/model/IProductBeanDAO.java
  Develop/src/tw/eeit117/wematch/product/model/IProductBeanService.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBeanDAO.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBeanService.java
Labels: enhancement

#79 Eason product searching function
  Develop/WebContent/WEB-INF/pages/ProductAddPage.jsp
  Develop/WebContent/WEB-INF/pages/ProductUpdatePage.jsp
  Develop/WebContent/WEB-INF/pages/ProductsBrowsePage.jsp
  Develop/WebContent/WEB-INF/pages/ProductsManagePage.jsp
  Develop/WebContent/WEB-INF/pages/ProductsSearchPage.jsp
  Develop/WebContent/js/ProductBrowserPage.js
  Develop/WebContent/js/ProductManagePage.js
  Develop/WebContent/js/ProductSearchPage.js
  Develop/src/tw/eeit117/wematch/product/controller/ProductController.java
  Develop/src/tw/eeit117/wematch/product/model/IProductBeanDAO.java
  Develop/src/tw/eeit117/wematch/product/model/IProductBeanService.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBeanDAO.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBeanService.java
Labels: enhancement

#95 fix the btn in manage and add search suggestion
  Develop/WebContent/WEB-INF/pages/ProductsBrowsePage.jsp
  Develop/WebContent/js/ProductBrowserPage.js
  Develop/WebContent/js/ProductManagePage.js
Labels: bug, enhancement

#102 Eason product sorting by price
  Develop/WebContent/WEB-INF/pages/ProductsBrowsePage.jsp
  Develop/WebContent/WEB-INF/pages/ProductsManagePage.jsp
  Develop/WebContent/js/ProductBrowserPage.js
  Develop/WebContent/js/ProductManagePage.js
  Develop/src/tw/eeit117/wematch/product/controller/ProductController.java
Labels: enhancement

#118 Eason product sortting by date
  Develop/SQLResource/create_table.sql
  Develop/WebContent/WEB-INF/pages/ProductExamPage.jsp
  Develop/WebContent/WEB-INF/pages/ProductsBrowsePage.jsp
  Develop/WebContent/WEB-INF/pages/ProductsManagePage.jsp
  Develop/WebContent/js/ProductBrowserPage.js
  Develop/WebContent/js/ProductManagePage.js
  Develop/pom.xml
  Develop/src/tw/eeit117/wematch/courses/controller/CoursesController.java
  Develop/src/tw/eeit117/wematch/courses/controller/CurriculumController.java
  Develop/src/tw/eeit117/wematch/product/controller/ProductController.java
  Develop/src/tw/eeit117/wematch/product/model/IProductBeanDAO.java
  Develop/src/tw/eeit117/wematch/product/model/IProductBeanService.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBean.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBeanDAO.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBeanService.java
Labels: enhancement

#132 Eason shopping cart backend
  Develop/WebContent/TransportInf.jsp
  Develop/WebContent/WEB-INF/pages/ProductsBrowsePage.jsp
  Develop/WebContent/WEB-INF/pages/ReceiverResult.jsp
  Develop/WebContent/WEB-INF/pages/ShoppingCartPage.jsp
  Develop/WebContent/WEB-INF/pages/TransportInf.jsp
  Develop/WebContent/WEB-INF/pages/header.jsp
  Develop/WebContent/js/ProductBrowserPage.js
  Develop/WebContent/js/ProductManagePage.js
  Develop/WebContent/js/ShoppingCartPage.js
  Develop/src/tw/eeit117/wematch/cart/controller/CartController.java
  Develop/src/tw/eeit117/wematch/cart/model/Receiver.java
  Develop/src/tw/eeit117/wematch/cart/model/ReceiverDao.java
  Develop/src/tw/eeit117/wematch/cart/model/ReceiverService.java
  Develop/src/tw/eeit117/wematch/product/controller/ProductController.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBeanDAO.java
Labels: enhancement

#133 prepare 0925 demo for shopping cart
  Develop/WebContent/TransportInf.jsp
  Develop/WebContent/WEB-INF/pages/ReceiverResult.jsp
  Develop/WebContent/WEB-INF/pages/ShoppingCartPage.jsp
  Develop/WebContent/WEB-INF/pages/TransportInf.jsp
  Develop/src/tw/eeit117/wematch/cart/controller/CartController.java
  Develop/src/tw/eeit117/wematch/product/TestProductsGenerator.java
Labels: enhancement

#135 Eason pass selected product info to the order
  Develop/WebContent/WEB-INF/pages/ProductAddPage.jsp
  Develop/WebContent/WEB-INF/pages/ProductExamPage.jsp
  Develop/WebContent/WEB-INF/pages/ProductUpdatePage.jsp
  Develop/WebContent/WEB-INF/pages/ShoppingCartPage.jsp
  Develop/WebContent/WEB-INF/pages/header.jsp
  Develop/WebContent/js/ShoppingCartPage.js
  Develop/src/tw/eeit117/wematch/cart/controller/CartController.java
  Develop/src/tw/eeit117/wematch/product/controller/ProductController.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBean.java
Labels: enhancement

#136 Eason payment checking page
  Develop/SQLResource/create_table.sql
  Develop/WebContent/WEB-INF/pages/ReceiverError.jsp
  Develop/WebContent/WEB-INF/pages/ShoppingCartPage.jsp
  Develop/src/tw/eeit117/wematch/cart/controller/CartController.java
  Develop/src/tw/eeit117/wematch/cart/model/Receiver.java
Labels: documentation

#137 Eason payment checking page
  Develop/WebContent/WEB-INF/pages/GreenTest.jsp
  Develop/WebContent/WEB-INF/pages/ShoppingCartPage.jsp
  Develop/WebContent/WEB-INF/pages/ShoppingPaymentPage.jsp
  Develop/WebContent/WEB-INF/pages/header.jsp
  Develop/pom.xml
  Develop/src/ecpay/payment/integration/AllInOne.java
  Develop/src/ecpay/payment/integration/AllInOneBase.java
  Develop/src/ecpay/payment/integration/config/EcpayConfig.java
  Develop/src/ecpay/payment/integration/config/EcpayPayment.xml
  Develop/src/ecpay/payment/integration/domain/ATMRequestObj.java
  Develop/src/ecpay/payment/integration/domain/AioCheckOutALL.java
  Develop/src/ecpay/payment/integration/domain/AioCheckOutATM.java
  Develop/src/ecpay/payment/integration/domain/AioCheckOutBARCODE.java
  Develop/src/ecpay/payment/integration/domain/AioCheckOutCVS.java
  Develop/src/ecpay/payment/integration/domain/AioCheckOutDevide.java
  Develop/src/ecpay/payment/integration/domain/AioCheckOutGooglePay.java
  Develop/src/ecpay/payment/integration/domain/AioCheckOutOneTime.java
  Develop/src/ecpay/payment/integration/domain/AioCheckOutPeriod.java
  Develop/src/ecpay/payment/integration/domain/AioCheckOutWebATM.java
  Develop/src/ecpay/payment/integration/domain/CVSOrBARCODERequestObj.java
  Develop/src/ecpay/payment/integration/domain/CaptureObj.java
  Develop/src/ecpay/payment/integration/domain/CreateServerOrderObj.java
  Develop/src/ecpay/payment/integration/domain/DoActionObj.java
  Develop/src/ecpay/payment/integration/domain/FundingReconDetailObj.java
  Develop/src/ecpay/payment/integration/domain/InvoiceObj.java
  Develop/src/ecpay/payment/integration/domain/QueryCreditCardPeriodInfoObj.java
  Develop/src/ecpay/payment/integration/domain/QueryTradeInfoObj.java
  Develop/src/ecpay/payment/integration/domain/QueryTradeObj.java
  Develop/src/ecpay/payment/integration/domain/TradeNoAioObj.java
  Develop/src/ecpay/payment/integration/ecpayOperator/EcpayFunction.java
  Develop/src/ecpay/payment/integration/ecpayOperator/PaymentVerifyBase.java
  Develop/src/ecpay/payment/integration/errorMsg/ErrorMessage.java
  Develop/src/ecpay/payment/integration/exception/EcpayException.java
  Develop/src/ecpay/payment/integration/vertification/VerifyAioCheckOut.java
  Develop/src/ecpay/payment/integration/vertification/VerifyCapture.java
  Develop/src/ecpay/payment/integration/vertification/VerifyCreateServerOrder.java
  Develop/src/ecpay/payment/integration/vertification/VerifyDoAction.java
  Develop/src/ecpay/payment/integration/vertification/VerifyFundingReconDetail.java
  Develop/src/ecpay/payment/integration/vertification/VerifyQueryCreditTrade.java
  Develop/src/ecpay/payment/integration/vertification/VerifyQueryTrade.java
  Develop/src/ecpay/payment/integration/vertification/VerifyQueryTradeInfo.java
  Develop/src/ecpay/payment/integration/vertification/VerifyTradeNoAio.java
  Develop/src/payment_conf.xml
  Develop/src/tw/eeit117/wematch/cart/controller/CartController.java
Labels: enhancement

#139 Eason ecpay payment conf path fix
  Develop/src/ecpay/payment/integration/AllInOneBase.java
  Develop/src/tw/eeit117/wematch/cart/controller/CartController.java
  Develop/src/tw/eeit117/wematch/product/controller/ProductController.java
Labels: enhancement

#142 Chiao shoppingcart
  Develop/WebContent/WEB-INF/pages/ShoppingCartPage.jsp
  Develop/WebContent/WEB-INF/pages/ShoppingPaymentPage.jsp
Labels: enhancement

#143 add the validation of product add and upate inputs
  Develop/WebContent/WEB-INF/pages/ProductAddPage.jsp
  Develop/WebContent/WEB-INF/pages/ProductUpdatePage.jsp
  Develop/WebContent/js/ProductAddPage.js
  Develop/WebContent/js/ProductUpdatePage.js
Labels: enhancement

#145 Eason user experience improvement
  Develop/WebContent/WEB-INF/pages/ProductExamPage.jsp
  Develop/WebContent/WEB-INF/pages/ProductsBrowsePage.jsp
  Develop/WebContent/WEB-INF/pages/ProductsManagePage.jsp
  Develop/WebContent/js/ProductBrowserPage.js
  Develop/WebContent/js/ProductExamPage.js
  Develop/WebContent/js/ProductManagePage.js
Labels: enhancement

#147 Eason product stock should change when sold
  Develop/WebContent/WEB-INF/pages/ProductAddPage.jsp
  Develop/WebContent/WEB-INF/pages/ProductUpdatePage.jsp
  Develop/WebContent/WEB-INF/pages/ProductsBrowsePage.jsp
  Develop/WebContent/WEB-INF/pages/ProductsManagePage.jsp
  Develop/WebContent/WEB-INF/pages/ShoppingCartPage.jsp
  Develop/WebContent/js/ProductBrowserPage.js
  Develop/WebContent/js/ProductManagePage.js
  Develop/WebContent/js/ProductUpdatePage.js
  Develop/WebContent/js/ShoppingCartPage.js
  Develop/src/tw/eeit117/wematch/cart/controller/CartController.java
  Develop/src/tw/eeit117/wematch/product/model/IProductBeanDAO.java
  Develop/src/tw/eeit117/wematch/product/model/IProductBeanService.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBeanDAO.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBeanService.java
Labels: enhancement

#149 Eason product arrival inform
  Develop/WebContent/WEB-INF/pages/header.jsp
  Develop/WebContent/js/ProductBrowserPage.js
  Develop/pom.xml
  Develop/src/mail.properties
  Develop/src/tw/eeit117/wematch/product/controller/ProductController.java
  Develop/src/tw/eeit117/wematch/product/model/IProductBeanDAO.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBeanDAO.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBeanService.java
  Develop/src/tw/wematch/util/Sender.java
Labels: enhancement

#151 Chi shoppingcart receiver validation
  Develop/WebContent/WEB-INF/pages/ProductsBrowsePage.jsp
  Develop/WebContent/WEB-INF/pages/ProductsManagePage.jsp
  Develop/WebContent/WEB-INF/pages/ShoppingCartBackStage.jsp
  Develop/WebContent/WEB-INF/pages/ShoppingCartPage.jsp
  Develop/WebContent/js/ShoppingCartPage.js
  Develop/resource/massager/massager0_d.jpg
  Develop/resource/massager/massager0_t.jpg
  Develop/src/tw/eeit117/wematch/product/TestProductsGenerator.java
Labels: enhancement

#154 Eason product arrival inform bugfix
  Develop/WebContent/js/ProductBrowserPage.js
  Develop/src/ecpay/payment/integration/AllInOneBase.java
  Develop/src/mail.properties
  Develop/src/tw/eeit117/wematch/product/controller/ProductController.java
  Develop/src/tw/wematch/util/Sender.java
Labels: enhancement

#157 code refinement in general
  Develop/WebContent/WEB-INF/pages/HomePage.jsp
  Develop/WebContent/WEB-INF/pages/MemberForgetAction.jsp
  Develop/WebContent/WEB-INF/pages/MemberForgot.jsp
  Develop/WebContent/WEB-INF/pages/ProductExamPage.jsp
  Develop/WebContent/WEB-INF/pages/ProductUpdatePage.jsp
  Develop/WebContent/WEB-INF/pages/VideoPage.jsp
  Develop/WebContent/WEB-INF/pages/header.jsp
  Develop/WebContent/WEB-INF/pages/headerout.jsp
  Develop/WebContent/WEB-INF/pages/index.jsp
  Develop/WebContent/WEB-INF/pages/registerPage.jsp
  Develop/WebContent/index.jsp
  Develop/WebContent/js/ProductBrowserPage.js
  Develop/WebContent/js/ProductManagePage.js
  Develop/src/Hibernate.properties
  Develop/src/tw/eeit117/wematch/cart/controller/CartController.java
  Develop/src/tw/eeit117/wematch/member/controller/MemberAdminController.java
  Develop/src/tw/eeit117/wematch/member/controller/MemberController.java
  Develop/src/tw/eeit117/wematch/product/controller/ProductController.java
  Develop/src/tw/wematch/util/OpenSessionViewFilter.java
Labels: bug, enhancement, invalid

#158 Eason product smart recommendation
  Develop/SQLResource/insert_table.sql
  Develop/WebContent/SignUpPage.jsp
  Develop/WebContent/WEB-INF/pages/ProductsBrowsePage.jsp
  Develop/WebContent/js/ProductChat.js
  Develop/src/tw/eeit117/wematch/product/chart/ProductMessageHandler.java
  Develop/src/tw/eeit117/wematch/product/chart/ProductServerAppConfigProvider.java
  Develop/src/tw/eeit117/wematch/product/chart/ProgrammaticEchoEnpoint.java
  Develop/src/tw/eeit117/wematch/product/model/ProductBean.java
Labels: enhancement

#161 Chiao shoppingcart add delete function
  Develop/WebContent/WEB-INF/pages/ShoppingCartPage.jsp
  Develop/WebContent/js/ShoppingCartPage.js
  Develop/src/tw/eeit117/wematch/cart/controller/CartController.java
Labels: enhancement

#159 change the name attribute to memberName
  Develop/WebContent/WEB-INF/pages/BookingBrowse3.jsp
  Develop/WebContent/WEB-INF/pages/Bookingadmin.jsp
  Develop/WebContent/WEB-INF/pages/MemberAdminPage_r.jsp
  Develop/WebContent/WEB-INF/pages/MemberAdminPage_u.jsp
  Develop/WebContent/WEB-INF/pages/MemberPage.jsp
  Develop/WebContent/WEB-INF/pages/VideoPage.jsp
Labels: bug, invalid
